[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "7VuVbxZZV5AVsGYUmhEa6gZPWU4dj5Nc2YEa8JJFDccq"

[registry]
url = "http://localhost:8899"

[provider]
cluster = "Localnet"
wallet = "/Users/miglesias/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
